### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ManReadApp** [ManReadApp/ManRead#1]
- [ ] Reader
  - [ ] finish infinite scroll in reader
  - [ ] modify image renderer (contrast...)
  - [ ] add manga/chapter info to reader
  - [ ] safe reading progress
  - [ ] optimize reader(everything is in an arc)
- [ ] Info page
- [ ] Add Manga page
- [ ] Add Chapter page
- [ ] Add Settings page
- [ ] Add token management page
- [ ] Search
  - [x] external search
  - [ ] add advanced search
    - [x] ~~Favorites~~
    - [ ] Reading
    - [x] ~~Title~~
    - [x] ~~Artist~~
    - [x] ~~Author~~
    - [x] ~~Uploader~~
    - [x] ~~Chapters~~
    - [x] ~~Uploaded~~
    - [x] ~~Kind~~
    - [x] ~~Source~~
    - [x] ~~Status~~
    - [x] ~~Tag~~
    - [x] ~~order by Created~~
    - [ ] order by Alphabetical
    - [x] ~~order by Updated~~
    - [x] ~~order by LastRead~~
    - [ ] order by Popularity
    - [x] ~~order by random~~
    - [x] ~~ilikearray function~~
  - [ ] simple (advanced) internal search
  - [ ] dispose of old images
- [ ] Add Now Reading page
- [ ] Add Favorites page 
- [ ] Add Encryption
- [ ] Downscale covers in search
- [ ] Finish search scraper
  - [x] ~~anilist~~
  - [x] ~~animeplanet~~
  - [x] myanimelist
  - [ ] manga-updates
  - [x] ~~kitsu~~
  - [x] ~~asura~~
  - [x] ~~custom~~
- [x] load fonts from server
- [x] fix gaps between letters
- [ ] Add manga type management page
- [ ] Add tag management page
- [ ] scrape/translate/colorize background automation
- [ ] Edit pages
- [ ] Login with ...
